### ISSUE TITLE
video.image() in HSVColorTracking example

### ISSUE THREAD

**Issue by aleatorictv** [atduskgreg/opencv-processing-book#2]
Hi! I had a problem running HSVColorTracking.pde as you've written it.  

line 26>> opencv.loadImage(video.image());
This threw an "unknown function 'image()' " error for me. 
I'm running Processing 2.0.3 on Mac OSX and also Windows 7.

I could resolve it in OSX by actually removing the '.image()' and just passing 'video'. (Not sure why that works but ...)

In Windows I had to switch the renderer from P2D to JAVA2D, then change line 26 to:
video.loadPixels();
opencv.loadImage(video.get());

This sounds like it has more to do with the Capture library or maybe differences in machines and webcams but I thought I'd throw it out there.  Thanks for your hard work!

**Comment by jorditost** [comment]
The same for me running Processing 2.0.3 on Mac OSX.

I had to use:

```
opencv.loadImage(video);
```

Instead of:

```
opencv.loadImage(video.image());
```

Take a look to the Processing Documentation:

http://processing.org/reference/libraries/video/Capture_read_.html

In the example it is implemented this way:

```
if (cam.available()) { 
    // Reads the new frame
    cam.read(); 
} 
image(cam, 0, 0);
```

In the code, the read() method is called under the captureEvent() function. But I'm not sure why :)

**Comment by atduskgreg** [comment]
Yeah, you guys were right about this. Not sure how that snuck in that way. Fixed now.
